### ISSUE TITLE
Select option lists not working on Windows Chrome - See angular {{$select.placeholder}}

### ISSUE THREAD

**Issue by sdoran** [CoolestProjects/platform#27]
On initial registration page i'm seeing angular syntax instead of values {{$select.placeholder}}

Console output
```
function f(a){D(a||{},this)}
vendor.js:98 Error: [ui.select:transcluded] http://errors.angularjs.org/1.2.28/ui.select/transcluded?p0=Expected%201%20.ui-select-choices%20but%20got%20'%7B0%7D'.&p1=0
    at https://platform.coolestprojects.org/scripts/ui.js:118:12
    at https://platform.coolestprojects.org/scripts/ui.js:917:19
    at https://platform.coolestprojects.org/scripts/vendor.js:52:367
    at https://platform.coolestprojects.org/scripts/vendor.js:54:217
    at w (https://platform.coolestprojects.org/scripts/vendor.js:58:29)
    at https://platform.coolestprojects.org/scripts/ui.js:897:9
    at J (https://platform.coolestprojects.org/scripts/vendor.js:60:373)
    at https://platform.coolestprojects.org/scripts/vendor.js:67:96
    at https://platform.coolestprojects.org/scripts/vendor.js:78:199
    at J (https://platform.coolestprojects.org/scripts/vendor.js:107:96) <div class="form-control cp-select ui-select-container ui-select-bootstrap dropdown ng-pristine ng-animate ng-valid-add" ng-class="{open: $select.open}" ng-model="gender.selected" title="Gender" style="transition-property: none; -webkit-transition-property: none;">
vendor.js:98 Error: [ui.select:transcluded] http://errors.angularjs.org/1.2.28/ui.select/transcluded?p0=Expected%201%20.ui-select-choices%20but%20got%20'%7B0%7D'.&p1=0
    at https://platform.coolestprojects.org/scripts/ui.js:118:12
    at https://platform.coolestprojects.org/scripts/ui.js:917:19
    at https://platform.coolestprojects.org/scripts/vendor.js:52:367
    at https://platform.coolestprojects.org/scripts/vendor.js:54:217
    at w (https://platform.coolestprojects.org/scripts/vendor.js:58:29)
    at https://platform.coolestprojects.org/scripts/ui.js:897:9
    at J (https://platform.coolestprojects.org/scripts/vendor.js:60:373)
    at https://platform.coolestprojects.org/scripts/vendor.js:67:96
    at https://platform.coolestprojects.org/scripts/vendor.js:78:199
    at J (https://platform.coolestprojects.org/scripts/vendor.js:107:96) <div class="form-control cp-select ui-select-container ui-select-bootstrap dropdown ng-pristine ng-animate ng-valid-add" ng-class="{open: $select.open}" ng-model="coderdojo.selected" title="CoderDojo" style="transition-property: none; -webkit-transition-property: none;">
vendor.js:98 Error: [ui.select:transcluded] http://errors.angularjs.org/1.2.28/ui.select/transcluded?p0=Expected%201%20.ui-select-choices%20but%20got%20'%7B0%7D'.&p1=0
    at https://platform.coolestprojects.org/scripts/ui.js:118:12
    at https://platform.coolestprojects.org/scripts/ui.js:917:19
    at https://platform.coolestprojects.org/scripts/vendor.js:52:367
    at https://platform.coolestprojects.org/scripts/vendor.js:54:217
    at w (https://platform.coolestprojects.org/scripts/vendor.js:58:29)
    at https://platform.coolestprojects.org/scripts/ui.js:897:9
    at J (https://platform.coolestprojects.org/scripts/vendor.js:60:373)
    at https://platform.coolestprojects.org/scripts/vendor.js:67:96
    at https://platform.coolestprojects.org/scripts/vendor.js:78:199
    at J (https://platform.coolestprojects.org/scripts/vendor.js:107:96) <div class="form-control cp-select ui-select-container ui-select-bootstrap dropdown ng-pristine ng-animate ng-valid-add" ng-class="{open: $select.open}" ng-model="maillist.selected" title="Main List" style="transition-property: none; -webkit-transition-property: none;">
vendor.js:98 Error: [ui.select:transcluded] http://errors.angularjs.org/1.2.28/ui.select/transcluded?p0=Expected%201%20.ui-select-choices%20but%20got%20'%7B0%7D'.&p1=0
    at https://platform.coolestprojects.org/scripts/ui.js:118:12
    at https://platform.coolestprojects.org/scripts/ui.js:917:19
    at https://platform.coolestprojects.org/scripts/vendor.js:52:367
    at https://platform.coolestprojects.org/scripts/vendor.js:54:217
    at w (https://platform.coolestprojects.org/scripts/vendor.js:58:29)
    at https://platform.coolestprojects.org/scripts/ui.js:897:9
    at J (https://platform.coolestprojects.org/scripts/vendor.js:60:373)
    at https://platform.coolestprojects.org/scripts/vendor.js:67:96
    at https://platform.coolestprojects.org/scripts/vendor.js:78:199
    at J (https://platform.coolestprojects.org/scripts/vendor.js:107:96) <div class="form-control cp-select ui-select-container ui-select-bootstrap dropdown ng-pristine ng-animate ng-valid-add" ng-class="{open: $select.open}" ng-model="category.selected" title="Gender" style="transition-property: none; -webkit-transition-property: none;">
vendor.js:98 Error: [ui.select:transcluded] http://errors.angularjs.org/1.2.28/ui.select/transcluded?p0=Expected%201%20.ui-select-choices%20but%20got%20'%7B0%7D'.&p1=0
    at https://platform.coolestprojects.org/scripts/ui.js:118:12
    at https://platform.coolestprojects.org/scripts/ui.js:917:19
    at https://platform.coolestprojects.org/scripts/vendor.js:52:367
    at https://platform.coolestprojects.org/scripts/vendor.js:54:217
    at w (https://platform.coolestprojects.org/scripts/vendor.js:58:29)
    at https://platform.coolestprojects.org/scripts/ui.js:897:9
    at J (https://platform.coolestprojects.org/scripts/vendor.js:60:373)
    at https://platform.coolestprojects.org/scripts/vendor.js:67:96
    at https://platform.coolestprojects.org/scripts/vendor.js:78:199
    at J (https://platform.coolestprojects.org/scripts/vendor.js:107:96) <div class="form-control cp-select ui-select-container ui-select-bootstrap dropdown ng-pristine ng-animate ng-valid-add" ng-class="{open: $select.open}" ng-model="groupproject.selected" title="Group Project" style="transition-property: none; -webkit-transition-property: none;">
vendor.js:98 TypeError: Cannot read property 'source' of undefined
    at Array.<anonymous> (ui.js:1441)
    at Object.<anonymous> (vendor.js:196)
    at h.$digest (vendor.js:116)
    at h.$apply (vendor.js:119)
    at m (vendor.js:78)
    at w (vendor.js:83)
    at XMLHttpRequest.B.onreadystatechange (vendor.js:85)
vendor.js:98 TypeError: Cannot read property 'itemName' of undefined
    at ui.js:1434
    at vendor.js:196
    at r (vendor.js:13)
    at $setViewValue (vendor.js:196)
    at Object.fn (ui.js:1464)
    at h.$digest (vendor.js:116)
    at h.$apply (vendor.js:119)
    at m (vendor.js:78)
    at w (vendor.js:83)
    at XMLHttpRequest.B.onreadystatechange (vendor.js:85)
vendor.js:98 TypeError: Cannot read property 'source' of undefined
    at Array.<anonymous> (ui.js:1441)
    at Object.<anonymous> (vendor.js:196)
    at h.$digest (vendor.js:116)
    at h.$apply (vendor.js:119)
    at m (vendor.js:78)
    at w (vendor.js:83)
    at XMLHttpRequest.B.onreadystatechange (vendor.js:85)
vendor.js:98 TypeError: Cannot read property 'itemName' of undefined
    at ui.js:1434
    at vendor.js:196
    at r (vendor.js:13)
    at $setViewValue (vendor.js:196)
    at Object.fn (ui.js:1464)
    at h.$digest (vendor.js:116)
    at h.$apply (vendor.js:119)
    at m (vendor.js:78)
    at w (vendor.js:83)
    at XMLHttpRequest.B.onreadystatechange (vendor.js:85)
vendor.js:98 TypeError: Cannot read property 'source' of undefined
    at Array.<anonymous> (ui.js:1441)
    at Object.<anonymous> (vendor.js:196)
    at h.$digest (vendor.js:116)
    at h.$apply (vendor.js:119)
    at m (vendor.js:78)
    at w (vendor.js:83)
    at XMLHttpRequest.B.onreadystatechange (vendor.js:85)
vendor.js:98 TypeError: Cannot read property 'itemName' of undefined
    at ui.js:1434
    at vendor.js:196
    at r (vendor.js:13)
    at $setViewValue (vendor.js:196)
    at Object.fn (ui.js:1464)
    at h.$digest (vendor.js:116)
    at h.$apply (vendor.js:119)
    at m (vendor.js:78)
    at w (vendor.js:83)
    at XMLHttpRequest.B.onreadystatechange (vendor.js:85)
vendor.js:98 TypeError: Cannot read property 'source' of undefined
    at Array.<anonymous> (ui.js:1441)
    at Object.<anonymous> (vendor.js:196)
    at h.$digest (vendor.js:116)
    at h.$apply (vendor.js:119)
    at m (vendor.js:78)
    at w (vendor.js:83)
    at XMLHttpRequest.B.onreadystatechange (vendor.js:85)
vendor.js:98 TypeError: Cannot read property 'itemName' of undefined
    at ui.js:1434
    at vendor.js:196
    at r (vendor.js:13)
    at $setViewValue (vendor.js:196)
    at Object.fn (ui.js:1464)
    at h.$digest (vendor.js:116)
    at h.$apply (vendor.js:119)
    at m (vendor.js:78)
    at w (vendor.js:83)
    at XMLHttpRequest.B.onreadystatechange (vendor.js:85)
vendor.js:98 TypeError: Cannot read property 'source' of undefined
    at Array.<anonymous> (ui.js:1441)
    at Object.<anonymous> (vendor.js:196)
    at h.$digest (vendor.js:116)
    at h.$apply (vendor.js:119)
    at m (vendor.js:78)
    at w (vendor.js:83)
    at XMLHttpRequest.B.onreadystatechange (vendor.js:85)
vendor.js:98 TypeError: Cannot read property 'itemName' of undefined
    at ui.js:1434
    at vendor.js:196
    at r (vendor.js:13)
    at $setViewValue (vendor.js:196)
    at Object.fn (ui.js:1464)
    at h.$digest (vendor.js:116)
    at h.$apply (vendor.js:119)
    at m (vendor.js:78)
    at w (vendor.js:83)
    at XMLHttpRequest.B.onreadystatechange (vendor.js:85)
angular-scroll.min.js.map:1 GET https://platform.coolestprojects.org/scripts/angular-scroll.min.js.map 404 (Not Found)
angular-sanitize.min.js.map:1 GET https://platform.coolestprojects.org/scripts/angular-sanitize.min.js.map 404 (Not Found)
```

**Comment by sdoran** [comment]
I can look into this... unable to figure out how to assign it to myself though :P

**Comment by alan-donnelly** [comment]
Does that happen every time, or only occasionally? Seems like it could be an XHR sometimes not completing?

**Comment by sdoran** [comment]
it's probably not loading the first time and then once some resources are
cached it loads after refresh

**Comment by noelking** [comment]
Looks like the same issue here as discussed on select-ui 

https://github.com/angular-ui/ui-select/issues/85

**Comment by sdoran** [comment]
Nice find. I can experiment rolling back a version.

**Comment by sdoran** [comment]
Just had a look there. Rolling back to 0.11.1 appears to resolve the issue although its difficult to test when i can't consistently reproduce. Don't have permission to push to this repo.

bower.json
```
"angular-ui-select": "~0.11.1"
```

**Comment by noelking** [comment]
Upgrade to angular 1.3.15 did not fix this issue

**Comment by sdoran** [comment]
I'm not reproducing it locally anymore... Have you resolved it since?

**Comment by sdoran** [comment]
Looks like the issue described here https://github.com/angular-ui/ui-select/issues/218

>  finally resolved the issue by copying the theme templates to be in-line angular script tags instead of loading them via an HTTP request. There was a strange race condition between compilation of the templates and transclusion of the drop-down items - this was the only thing that was able to fix the problem.

**Comment by noelking** [comment]
Excellent thanks Sarah

**Comment by noelking** [comment]
Sarah if you get a chance could you try this as it did not work for me locally, the best way to test is in private or incognito growing modes

**Comment by sdoran** [comment]
Yeah will try tomorrow. I couldn't reproduce at all locally today so didn't
want to commit blind.

**Comment by sdoran** [comment]
Didn't work for me either... Need to find another way to ensure templates get loaded first.

**Comment by noelking** [comment]
I have made update here on the suggestion about loading the templates in script tags which on my current testing has worked, thanks sarah for the linking of the issue.  Please test yourself tomorrow and let me know if it returns.

**Comment by noelking** [comment]
sadly not fixed on further testing

**Comment by sdoran** [comment]
No probs, I'll  have a look at lunchtime today.

**Comment by noelking** [comment]
Make a fix here which works in our scenario, if the error occurs it refreshes the screen. There is definitely a race condition here which I have not had the time to resolved.  In the interest of moving the features forward I added this fix and I am going to leave this issue open to re-investigate a more attractive solution in the future.
